kind: Service
apiVersion: v1
metadata:
  name: "demo-app"
spec:
  selector:
    app: "demo-app"
    secure: "enabled"
  ports:
    - protocol: "TCP"
      port: 443
      targetPort: 443
  type: LoadBalancer
